name: Deploy Website to AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  S3_BUCKET: rohan-devops-cicd-website-2026
  CLOUDFRONT_DISTRIBUTION_ID: EVN6RYCBFXQYD

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run tests
        run: npm test


  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create deployment package
        run: |
          mkdir build
          cp index.html build/
          cp style.css build/
          cp script.js build/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-build
          path: build/


  deploy:
  name: Deploy to AWS
  needs: build
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Download build artifact
      uses: actions/download-artifact@v5
      with:
        name: website-build
        path: build

    - name: Debug OIDC token
      uses: github/actions-oidc-debugger@main

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: arn:aws:iam::953216549657:role/GitHubActionsDevOpsDeploymentRole
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy website to S3
      run: |
        aws s3 sync build/ s3://${{ env.S3_BUCKET }}/ --delete

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"